public class MySampleApexClass {       //Class definition and body
   public static Integer myValue = 0;  //Class Member variable
   public static String myString = ''; //Class Member variable
   public static String myStrin5 = ''; //Class Member variable
   public static String myStrin7 = ''; //Class Member variable
   public static String variable3 = ''; //Class Member variable
   public static String variable4 = ''; //Class Member variable
   public static String variable5 = ''; //Class Member variable
   public static String myStrin3 = ''; //Class Member variable
   public static String myString2 = ''; //Class Member variable
   
   public static Integer getCalculatedValue () {
   // Method definition and body
   // do some calculation
      myValue = myValue+10;
      testing;
      testing2;
      return myValue;
   }
}